### PR TITLE
[Wip] Switch to Borg Backup Python Script from foxxx0

### PR DESCRIPTION
**Pull request by sebastianrakel**

### CODE REVIEW

**Comment by bastelfreak** [comment]
@sebastianrakel should we close the PR?

**Comment by sebastianrakel** [comment]
I think we should keep it open, because the script is not perfect till now. And is missing some features

We need more @foxxx0 Power on this!

**Comment by foxxx0** [comment]
it's been on my todo for quite some time now...

**Comment by igalic** [comment]
@foxxx0 do you have time to take this over?

**Comment by foxxx0** [comment]
Still haven't had time to work on the script further... and I likely won't for at least another couple of weeks.

**Pull request closed without merging**
