### PR TITLE
modulesync 2.10.1

### PR DESCRIPTION
**Pull request by dhoppe**

### CODE REVIEW

**Comment by bastelfreak** [comment]
anybody has an idea why this fails? I'm unable to reproduce this locally.

**Comment by dhoppe** [comment]
@bastelfreak I have no idea why it is failing back to FacterDB 3.1, 3.7 and 3.8, but these versions do not provide any facts for Ubuntu 18.04.

**Comment by bastelfreak** [comment]
My guess is that Gentoo fact sets are missing here. It might be fixed with https://github.com/camptocamp/facterdb/pull/140/commits/7575b3bb62086e67f1b4df93cf1bc1aa88a88b6c

**Comment by dhoppe** [comment]
Good catch. FacterDB breaks so many things. 😕

**Comment by bastelfreak** [comment]
so if we now could know which factset is actually failing

**Pull request merged**
